// Products actions types
export const ADD_PRODUCTS = 'LOAD_PRODUCTS'
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS'
export const START_ROTATING_SPINNER = 'START_ROTATING_SPINNER'
export const STOP_ROTATING_SPINNER = 'STOP_ROTATING_SPINNER'
export const HANDLE_INPUT_TEXT_CHANGE = 'HANDLE_INPUT_TEXT_CHANGE'
export const HANDLE_FILTER_CHANGE = 'HANDLE_FILTER_CHANGE'
export const HANDLE_SORT_BY_PRICE = 'HANDLE_SORT_BY_PRICE'
export const HANDLE_ACTIVE_PAGE_CHANGE = 'HANDLE_ACTIVE_PAGE_CHANGE'

// Stores actions types
export const ADD_STORES = 'ADD_STORES'

// Categories products types
export const ADD_CATEGORIES_PRODUCTS = 'ADD_CATEGORIES_PRODUCTS'
export const START_CATEGORIES_ROTATING_SPINNER = 'START_CATEGORIES_ROTATING_SPINNER'
export const STOP_CATEGORIES_ROTATING_SPINNER = 'STOP_CATEGORIES_ROTATING_SPINNER'
export const HANDLE_CATEGORIES_FILTER_CHANGE = 'HANDLE_CATEGORIES_FILTER_CHANGE'
export const HANDLE_CATEGORIES_SORT_BY_PRICE = 'HANDLE_CATEGORIES_SORT_BY_PRICE'
export const HANDLE_CATEGORIES_ACTIVE_PAGE_CHANGE = 'HANDLE_CATEGORIES_ACTIVE_PAGE_CHANGE'