// Products actions types
export const ADD_PRODUCTS = 'LOAD_PRODUCTS'
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS'
export const START_ROTATING_SPINNER = 'START_ROTATING_SPINNER'
export const STOP_ROTATING_SPINNER = 'STOP_ROTATING_SPINNER'
export const HANDLE_INPUT_TEXT_CHANGE = 'HANDLE_INPUT_TEXT_CHANGE'
export const HANDLE_FILTER_CHANGE = 'HANDLE_FILTER_CHANGE'
export const HANDLE_ACTIVE_PAGE_CHANGE = 'HANDLE_ACTIVE_PAGE_CHANGE'
export const SORT_PRODUCTS_DESC_BY_PRICE = 'SORT_PRODUCTS_DESC_BY_PRICE'
export const SORT_PRODUCTS_ASC_BY_PRICE = 'SORT_PRODUCTS_ASC_BY_PRICE'
export const NULL_SORT = 'NULL_SORT'

// Stores actions types
export const ADD_STORES = 'ADD_STORES'